version: '3'

services:
  app:
    image: node:carbon
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - .:/app
    command: >
      bash -c "npm install &&
               npm run build &&
               npm start -- -p 80"
